"""
Shared utilities package.
"""

from .constants import (
    EXPORT_DIR,
    BASE_URL,
    FILES_DELAY,
    DOCS_TEMPLATE_PATH,
    PERSISTENT_FILES,
    TABLE_SEPARATOR_RE,
    IMAGE_SOURCE_UNSPLASH,
    IMAGE_SOURCE_PEXELS,
    IMAGE_SOURCE_LOCAL_SD,
    FORMAT_PDF,
    FORMAT_DOCX,
    FORMAT_XLSX,
    FORMAT_PPTX,
    FORMAT_CSV,
    FORMAT_TXT,
    FORMAT_XML,
)
from .utils import (
    _public_url,
    _generate_unique_folder,
    _generate_filename,
    _cleanup_files,
    render_text_with_emojis,
    _extract_paragraph_style_info,
    _extract_cell_style_info,
    dynamic_font_size,
    _resolve_log_level,
)
from .styles import (
    styles,
    get_table_style,
)
from .images import (
    search_image,
    search_local_sd,
    search_unsplash,
    search_pexels,
)
from .types import (
    BLOCK_TITLE,
    BLOCK_SECTION,
    BLOCK_PARAGRAPH,
    BLOCK_HEADING,
    BLOCK_SUBHEADING,
    BLOCK_BULLET,
    BLOCK_LIST,
    BLOCK_TABLE,
    BLOCK_IMAGE,
    BLOCK_SOURCES,
    BLOCK_LABEL_PARAGRAPH,
    PARAGRAPH_TYPES,
    SOURCE_TYPES,
    FORMAT_PDF,
    FORMAT_DOCX,
    FORMAT_XLSX,
    FORMAT_PPTX,
    FORMAT_CSV,
    FORMAT_TXT,
    FORMAT_XML,
    IMAGE_POS_LEFT,
    IMAGE_POS_RIGHT,
    IMAGE_POS_TOP,
    IMAGE_POS_BOTTOM,
    IMAGE_SIZE_SMALL,
    IMAGE_SIZE_MEDIUM,
    IMAGE_SIZE_LARGE,
)

__all__ = [
    # Constants
    "EXPORT_DIR",
    "BASE_URL",
    "FILES_DELAY",
    "DOCS_TEMPLATE_PATH",
    "PERSISTENT_FILES",
    "TABLE_SEPARATOR_RE",
    "IMAGE_SOURCE_UNSPLASH",
    "IMAGE_SOURCE_PEXELS",
    "IMAGE_SOURCE_LOCAL_SD",
    "FORMAT_PDF",
    "FORMAT_DOCX",
    "FORMAT_XLSX",
    "FORMAT_PPTX",
    "FORMAT_CSV",
    "FORMAT_TXT",
    "FORMAT_XML",
    # Utils
    "_public_url",
    "_generate_unique_folder",
    "_generate_filename",
    "_cleanup_files",
    "render_text_with_emojis",
    "_extract_paragraph_style_info",
    "_extract_cell_style_info",
    "dynamic_font_size",
    "_resolve_log_level",
    # Images
    "search_image",
    "search_local_sd",
    "search_unsplash",
    "search_pexels",
    # Styles
    "styles",
    "get_table_style",
    # Types
    "BLOCK_TITLE",
    "BLOCK_SECTION",
    "BLOCK_PARAGRAPH",
    "BLOCK_HEADING",
    "BLOCK_SUBHEADING",
    "BLOCK_BULLET",
    "BLOCK_LIST",
    "BLOCK_TABLE",
    "BLOCK_IMAGE",
    "BLOCK_SOURCES",
    "BLOCK_LABEL_PARAGRAPH",
    "PARAGRAPH_TYPES",
    "SOURCE_TYPES",
    "IMAGE_POS_LEFT",
    "IMAGE_POS_RIGHT",
    "IMAGE_POS_TOP",
    "IMAGE_POS_BOTTOM",
    "IMAGE_SIZE_SMALL",
    "IMAGE_SIZE_MEDIUM",
    "IMAGE_SIZE_LARGE",
]